---
- name: Launch instance(s)
  hosts: localhost
  become: no
  connection: local
  gather_facts: no
  vars_files:
  - vars.yml
  vars:
    os_libvirt_storage_pool: "{{ libvirt_storage_pool | default('images') }}"
    os_libvirt_storage_pool_path: "{{ libvirt_storage_pool_path | default('/var/lib/libvirt/images') }}"
    os_libvirt_network: "{{ libvirt_network | default('default') }}"
    image_url: "{{ image.url }}"
    image_sha256: "{{ image.sha256 }}"
    image_name: "{{ image.name }}"
    image_compression: "{{ image.compression }}"
  tasks:

  - name: purge
    shell: for i in $(sudo virsh list | awk '/plop|plip+/{print $2}') ;do sudo virsh destroy $i; done 

  - include: tasks/configure_libvirt.yml

  - include: ../../common/kubernetes-cluster/tasks/set_etcd_launch_facts.yml
  - include: tasks/launch_instances.yml
    vars:
      instances: "{{ etcd_names }}"
      cluster: "{{ cluster_id }}"
      type: "{{ k8s_type }}"
      g_sub_host_type: "default"

  - include: ../../common/kubernetes-cluster/tasks/set_master_launch_facts.yml
  - include: tasks/launch_instances.yml
    vars:
      instances: "{{ master_names }}"
      cluster: "{{ cluster_id }}"
      type: "{{ k8s_type }}"
      g_sub_host_type: "default"

  - include: ../../common/kubernetes-cluster/tasks/set_node_launch_facts.yml
    vars:
      type: "compute"
      count: "{{ num_nodes }}"
  - include: tasks/launch_instances.yml
    vars:
      instances: "{{ node_names }}"
      cluster: "{{ cluster_id }}"
      type: "{{ k8s_type }}"
      g_sub_host_type: "{{ sub_host_type }}"

  - include: ../../common/kubernetes-cluster/tasks/set_node_launch_facts.yml
    vars:
      type: "infra"
      count: "{{ num_infra }}"
  - include: tasks/launch_instances.yml
    vars:
      instances: "{{ node_names }}"
      cluster: "{{ cluster_id }}"
      type: "{{ k8s_type }}"
      g_sub_host_type: "{{ sub_host_type }}"

- include: config.yml

#- include: list.yml
